[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # 個別の関数の設定
  [functions."*"]
    node_version = 20
    # ★★★ タイムアウトを60秒に延長します ★★★
    timeout = 60